### PR TITLE
Change the main image

### LINKED ISSUE #22: Change the main image

### PR DESCRIPTION
**Pull request by Tarik-Alaiwi-dev**

### CODE REVIEW

**Review by Stimm147 — APPROVED** [review]
Well cropped 👍

**Comment by Perunio** [comment]
Looks good.

**Review by remigiuszsek — APPROVED** [review]
It's much better 💪

**Comment by KTFish** [comment]
For now it is sufficient. Thansk for the upgrade!

**Review by KTFish — APPROVED** [review]

**Pull request merged**
